// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_upload_file_api_container__container_name__fs_upload__post
 */
export type BodyUploadFileApiContainerContainerNameFsUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CPUHardwareResponse
 */
export type CpuHardwareResponse = {
    /**
     * Architecture
     */
    architecture: string;
    /**
     * Cpu Count
     */
    cpu_count: number;
    /**
     * Model Name
     */
    model_name: string;
    /**
     * Threads Per Core
     */
    threads_per_core: number;
};

/**
 * ContainerCreateRequest
 */
export type ContainerCreateRequest = {
    /**
     * Server Name
     */
    server_name: string;
    /**
     * Template
     */
    template: string;
    /**
     * Port
     */
    port: {
        [key: string]: number | null;
    } | null;
    /**
     * Env
     */
    env: {
        [key: string]: string;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HardwareInfoResponse
 */
export type HardwareInfoResponse = {
    cpu: CpuHardwareResponse;
    /**
     * Mem
     */
    mem: number;
};

/**
 * StringListResponse
 */
export type StringListResponse = {
    /**
     * Values
     */
    values: Array<string>;
};

/**
 * Template
 */
export type Template = {
    /**
     * Name
     * Template name
     */
    name: string;
    /**
     * Image
     * Docker image name
     */
    image: string;
    /**
     * Tags
     * Comma-separated tags for the template
     */
    tags: string | null;
    /**
     * Default Env
     * JSON string of default environment variables
     */
    default_env: string | null;
    /**
     * Additional Env
     * JSON string of environment variables that will be added to server creator
     */
    additional_env: string | null;
    /**
     * Resource Min Cpu
     * Minimum CPU resources required
     */
    resource_min_cpu: number | null;
    /**
     * Resource Min Disk
     * Minimum Disk resources required
     */
    resource_min_disk: number | null;
    /**
     * Resource Min Mem
     * Minimum Memory resources required
     */
    resource_min_mem: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListContainersApiContainerListGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/container/list';
};

export type ListContainersApiContainerListGetResponses = {
    /**
     * Successful Response
     */
    200: StringListResponse;
};

export type ListContainersApiContainerListGetResponse = ListContainersApiContainerListGetResponses[keyof ListContainersApiContainerListGetResponses];

export type GetContainerApiContainerNameGetData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/container/{name}';
};

export type GetContainerApiContainerNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContainerApiContainerNameGetError = GetContainerApiContainerNameGetErrors[keyof GetContainerApiContainerNameGetErrors];

export type GetContainerApiContainerNameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StartContainerApiContainerNameStartGetData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/container/{name}/start';
};

export type StartContainerApiContainerNameStartGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartContainerApiContainerNameStartGetError = StartContainerApiContainerNameStartGetErrors[keyof StartContainerApiContainerNameStartGetErrors];

export type StartContainerApiContainerNameStartGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StopContainerApiContainerNameStopGetData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/container/{name}/stop';
};

export type StopContainerApiContainerNameStopGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopContainerApiContainerNameStopGetError = StopContainerApiContainerNameStopGetErrors[keyof StopContainerApiContainerNameStopGetErrors];

export type StopContainerApiContainerNameStopGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateContainerApiContainerCreateTemplateNamePostData = {
    body: ContainerCreateRequest;
    path?: never;
    query?: never;
    url: '/api/container/create/{template_name}';
};

export type CreateContainerApiContainerCreateTemplateNamePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateContainerApiContainerCreateTemplateNamePostError = CreateContainerApiContainerCreateTemplateNamePostErrors[keyof CreateContainerApiContainerCreateTemplateNamePostErrors];

export type CreateContainerApiContainerCreateTemplateNamePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetContainerStatusApiContainerContainerNameStatusGetData = {
    body?: never;
    path: {
        /**
         * Container Name
         */
        container_name: string;
    };
    query?: never;
    url: '/api/container/{container_name}/status';
};

export type GetContainerStatusApiContainerContainerNameStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContainerStatusApiContainerContainerNameStatusGetError = GetContainerStatusApiContainerContainerNameStatusGetErrors[keyof GetContainerStatusApiContainerContainerNameStatusGetErrors];

export type GetContainerStatusApiContainerContainerNameStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetLogMessageApiContainerContainerNameLogsGetData = {
    body?: never;
    path: {
        /**
         * Container Name
         */
        container_name: string;
    };
    query?: {
        /**
         * Line Count
         */
        line_count?: number | null;
    };
    url: '/api/container/{container_name}/logs';
};

export type GetLogMessageApiContainerContainerNameLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLogMessageApiContainerContainerNameLogsGetError = GetLogMessageApiContainerContainerNameLogsGetErrors[keyof GetLogMessageApiContainerContainerNameLogsGetErrors];

export type GetLogMessageApiContainerContainerNameLogsGetResponses = {
    /**
     * Response Get Log Message Api Container  Container Name  Logs Get
     * Successful Response
     */
    200: Array<string>;
};

export type GetLogMessageApiContainerContainerNameLogsGetResponse = GetLogMessageApiContainerContainerNameLogsGetResponses[keyof GetLogMessageApiContainerContainerNameLogsGetResponses];

export type GetDirectoryFilenamesApiContainerContainerNameFsListGetData = {
    body?: never;
    path: {
        /**
         * Container Name
         */
        container_name: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/api/container/{container_name}/fs/list';
};

export type GetDirectoryFilenamesApiContainerContainerNameFsListGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDirectoryFilenamesApiContainerContainerNameFsListGetError = GetDirectoryFilenamesApiContainerContainerNameFsListGetErrors[keyof GetDirectoryFilenamesApiContainerContainerNameFsListGetErrors];

export type GetDirectoryFilenamesApiContainerContainerNameFsListGetResponses = {
    /**
     * Response Get Directory Filenames Api Container  Container Name  Fs List Get
     * Successful Response
     */
    200: Array<string> | null;
};

export type GetDirectoryFilenamesApiContainerContainerNameFsListGetResponse = GetDirectoryFilenamesApiContainerContainerNameFsListGetResponses[keyof GetDirectoryFilenamesApiContainerContainerNameFsListGetResponses];

export type ReadFileApiContainerContainerNameFsGetData = {
    body?: never;
    path: {
        /**
         * Container Name
         */
        container_name: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/api/container/{container_name}/fs';
};

export type ReadFileApiContainerContainerNameFsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileApiContainerContainerNameFsGetError = ReadFileApiContainerContainerNameFsGetErrors[keyof ReadFileApiContainerContainerNameFsGetErrors];

export type ReadFileApiContainerContainerNameFsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadFileApiContainerContainerNameFsUploadPostData = {
    body: BodyUploadFileApiContainerContainerNameFsUploadPost;
    path: {
        /**
         * Container Name
         */
        container_name: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/api/container/{container_name}/fs/upload/';
};

export type UploadFileApiContainerContainerNameFsUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileApiContainerContainerNameFsUploadPostError = UploadFileApiContainerContainerNameFsUploadPostErrors[keyof UploadFileApiContainerContainerNameFsUploadPostErrors];

export type UploadFileApiContainerContainerNameFsUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteFileApiContainerContainerNameFsDeletePostData = {
    body?: never;
    path: {
        /**
         * Container Name
         */
        container_name: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/api/container/{container_name}/fs/delete/';
};

export type DeleteFileApiContainerContainerNameFsDeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFileApiContainerContainerNameFsDeletePostError = DeleteFileApiContainerContainerNameFsDeletePostErrors[keyof DeleteFileApiContainerContainerNameFsDeletePostErrors];

export type DeleteFileApiContainerContainerNameFsDeletePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SendCommandApiContainerContainerNameCommandGetData = {
    body?: never;
    path: {
        /**
         * Container Name
         */
        container_name: string;
    };
    query: {
        /**
         * Command
         */
        command: string;
    };
    url: '/api/container/{container_name}/command';
};

export type SendCommandApiContainerContainerNameCommandGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendCommandApiContainerContainerNameCommandGetError = SendCommandApiContainerContainerNameCommandGetErrors[keyof SendCommandApiContainerContainerNameCommandGetErrors];

export type SendCommandApiContainerContainerNameCommandGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteContainerApiContainerContainerNameDeleteGetData = {
    body?: never;
    path: {
        /**
         * Container Name
         */
        container_name: string;
    };
    query?: never;
    url: '/api/container/{container_name}/delete';
};

export type DeleteContainerApiContainerContainerNameDeleteGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteContainerApiContainerContainerNameDeleteGetError = DeleteContainerApiContainerContainerNameDeleteGetErrors[keyof DeleteContainerApiContainerContainerNameDeleteGetErrors];

export type DeleteContainerApiContainerContainerNameDeleteGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListTemplatesApiTemplateListGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/template/list';
};

export type ListTemplatesApiTemplateListGetResponses = {
    /**
     * Successful Response
     */
    200: StringListResponse;
};

export type ListTemplatesApiTemplateListGetResponse = ListTemplatesApiTemplateListGetResponses[keyof ListTemplatesApiTemplateListGetResponses];

export type GetTemplateNameApiTemplateNameGetData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/template/{name}';
};

export type GetTemplateNameApiTemplateNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTemplateNameApiTemplateNameGetError = GetTemplateNameApiTemplateNameGetErrors[keyof GetTemplateNameApiTemplateNameGetErrors];

export type GetTemplateNameApiTemplateNameGetResponses = {
    /**
     * Successful Response
     */
    200: Template;
};

export type GetTemplateNameApiTemplateNameGetResponse = GetTemplateNameApiTemplateNameGetResponses[keyof GetTemplateNameApiTemplateNameGetResponses];

export type AddTemplateApiTemplateCreatePostData = {
    body: Template;
    path?: never;
    query?: never;
    url: '/api/template/create';
};

export type AddTemplateApiTemplateCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddTemplateApiTemplateCreatePostError = AddTemplateApiTemplateCreatePostErrors[keyof AddTemplateApiTemplateCreatePostErrors];

export type AddTemplateApiTemplateCreatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteTemplateApiTemplateNameDeletePostData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/template/{name}/delete';
};

export type DeleteTemplateApiTemplateNameDeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTemplateApiTemplateNameDeletePostError = DeleteTemplateApiTemplateNameDeletePostErrors[keyof DeleteTemplateApiTemplateNameDeletePostErrors];

export type DeleteTemplateApiTemplateNameDeletePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HardwareApiSystemHardwareGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/hardware';
};

export type HardwareApiSystemHardwareGetResponses = {
    /**
     * Successful Response
     */
    200: HardwareInfoResponse;
};

export type HardwareApiSystemHardwareGetResponse = HardwareApiSystemHardwareGetResponses[keyof HardwareApiSystemHardwareGetResponses];

export type PingApiSystemPingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/ping';
};

export type PingApiSystemPingGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://nathan.local:8000' | (string & {});
};
