// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AddNodeData, AddNodeErrors, AddNodeResponses, AddTemplateData, AddTemplateErrors, AddTemplateResponses, CreateServerData, CreateServerErrors, CreateServerResponses, CreateUserAccountData, CreateUserAccountErrors, CreateUserAccountResponses, DeleteFileData, DeleteFileErrors, DeleteFileResponses, DeleteNodeData, DeleteNodeErrors, DeleteNodeResponses, DeleteServerData, DeleteServerErrors, DeleteServerResponses, DeleteTemplateData, DeleteTemplateErrors, DeleteTemplateResponses, DeleteUserAccountData, DeleteUserAccountResponses, DiskUsageData, DiskUsageErrors, DiskUsageResponses, GetArchiveData, GetArchiveErrors, GetArchiveResponses, GetNodeData, GetNodeErrors, GetNodeResponses, GetServerInfoData, GetServerInfoErrors, GetServerInfoResponses, GetServerStatusData, GetServerStatusErrors, GetServerStatusResponses, GetTemplateData, GetTemplateErrors, GetTemplateResponses, GetUserData, GetUserResponses, HandleHttpGetData, HandleHttpGetErrors, HandleHttpGetResponses, HandleHttpPostData, HandleHttpPostResponses, LoginUserData, LoginUserErrors, LoginUserResponses, LogoutUserData, LogoutUserResponses, ReadFileData, ReadFileErrors, ReadFileResponses, RefreshTokenData, RefreshTokenResponses, RuntimeData, RuntimeErrors, RuntimeResponses, SearchData, SearchFsData, SearchFsErrors, SearchFsResponses, SearchNodesData, SearchNodesResponses, SearchResponses, SearchServersData, SearchServersResponses, SearchTemplatesData, SearchTemplatesResponses, SendCommandData, SendCommandErrors, SendCommandResponses, StartServerData, StartServerErrors, StartServerResponses, StopServerData, StopServerErrors, StopServerResponses, UpdateTemplateData, UpdateTemplateErrors, UpdateTemplateResponses, UploadFileData, UploadFileErrors, UploadFileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Add Template
 * add a new template
 */
export const addTemplate = <ThrowOnError extends boolean = false>(options: Options<AddTemplateData, ThrowOnError>) => {
    return (options.client ?? client).post<AddTemplateResponses, AddTemplateErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/templates/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Template
 * get a template by id
 */
export const getTemplate = <ThrowOnError extends boolean = false>(options: Options<GetTemplateData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTemplateResponses, GetTemplateErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/templates/{template_id}',
        ...options
    });
};

/**
 * Update Template
 * update a template by id
 */
export const updateTemplate = <ThrowOnError extends boolean = false>(options: Options<UpdateTemplateData, ThrowOnError>) => {
    return (options.client ?? client).patch<UpdateTemplateResponses, UpdateTemplateErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/templates/{template_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Template
 * delete a template by name
 */
export const deleteTemplate = <ThrowOnError extends boolean = false>(options: Options<DeleteTemplateData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteTemplateResponses, DeleteTemplateErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/templates/{name}/delete',
        ...options
    });
};

/**
 * Delete User Account
 * delete current user account
 */
export const deleteUserAccount = <ThrowOnError extends boolean = false>(options?: Options<DeleteUserAccountData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteUserAccountResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/',
        ...options
    });
};

/**
 * Create User Account
 * create a new user account
 */
export const createUserAccount = <ThrowOnError extends boolean = false>(options: Options<CreateUserAccountData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateUserAccountResponses, CreateUserAccountErrors, ThrowOnError>({
        url: '/users/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Refresh Token
 * refresh access token using refresh token
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options?: Options<RefreshTokenData, ThrowOnError>) => {
    return (options?.client ?? client).post<RefreshTokenResponses, unknown, ThrowOnError>({
        url: '/users/refresh',
        ...options
    });
};

/**
 * Login User
 * login user, return access token and set refresh token to cookie
 */
export const loginUser = <ThrowOnError extends boolean = false>(options: Options<LoginUserData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginUserResponses, LoginUserErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/users/token',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Logout User
 * logout user, delete access token cookie
 */
export const logoutUser = <ThrowOnError extends boolean = false>(options?: Options<LogoutUserData, ThrowOnError>) => {
    return (options?.client ?? client).post<LogoutUserResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/revoke',
        ...options
    });
};

/**
 * Get User
 * get current user information
 */
export const getUser = <ThrowOnError extends boolean = false>(options?: Options<GetUserData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me',
        ...options
    });
};

/**
 * Create Server
 * Create a new server
 */
export const createServer = <ThrowOnError extends boolean = false>(options: Options<CreateServerData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateServerResponses, CreateServerErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Server
 * Delete a specific server
 */
export const deleteServer = <ThrowOnError extends boolean = false>(options: Options<DeleteServerData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteServerResponses, DeleteServerErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers/{server_id}',
        ...options
    });
};

/**
 * Get Server Info
 * Get information about a specific server
 */
export const getServerInfo = <ThrowOnError extends boolean = false>(options: Options<GetServerInfoData, ThrowOnError>) => {
    return (options.client ?? client).get<GetServerInfoResponses, GetServerInfoErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers/{server_id}',
        ...options
    });
};

/**
 * Start Server
 * Start a specific server
 */
export const startServer = <ThrowOnError extends boolean = false>(options: Options<StartServerData, ThrowOnError>) => {
    return (options.client ?? client).post<StartServerResponses, StartServerErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers/{server_id}/start',
        ...options
    });
};

/**
 * Stop Server
 * Stop a specific server
 */
export const stopServer = <ThrowOnError extends boolean = false>(options: Options<StopServerData, ThrowOnError>) => {
    return (options.client ?? client).post<StopServerResponses, StopServerErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers/{server_id}/stop',
        ...options
    });
};

/**
 * Get Server Status
 * Get the running status of a specific server
 */
export const getServerStatus = <ThrowOnError extends boolean = false>(options: Options<GetServerStatusData, ThrowOnError>) => {
    return (options.client ?? client).get<GetServerStatusResponses, GetServerStatusErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers/{server_id}/status',
        ...options
    });
};

/**
 * Send Command
 */
export const sendCommand = <ThrowOnError extends boolean = false>(options: Options<SendCommandData, ThrowOnError>) => {
    return (options.client ?? client).post<SendCommandResponses, SendCommandErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers/{server_id}/command',
        ...options
    });
};

/**
 * Add Node
 * add a new node
 */
export const addNode = <ThrowOnError extends boolean = false>(options: Options<AddNodeData, ThrowOnError>) => {
    return (options.client ?? client).post<AddNodeResponses, AddNodeErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/nodes/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Node
 * delete a node by name
 */
export const deleteNode = <ThrowOnError extends boolean = false>(options: Options<DeleteNodeData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteNodeResponses, DeleteNodeErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/nodes/{node_id}',
        ...options
    });
};

/**
 * Get Node
 * return hardware information in form of a Nodes object
 * fields: id, name, architecture, cpu_cores, memory, disk, cpu_name
 */
export const getNode = <ThrowOnError extends boolean = false>(options: Options<GetNodeData, ThrowOnError>) => {
    return (options.client ?? client).get<GetNodeResponses, GetNodeErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/nodes/{node_id}',
        ...options
    });
};

/**
 * Disk Usage
 * return disk usage in bytes (used, total)
 */
export const diskUsage = <ThrowOnError extends boolean = false>(options: Options<DiskUsageData, ThrowOnError>) => {
    return (options.client ?? client).get<DiskUsageResponses, DiskUsageErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/nodes/{node_id}/disk_usage',
        ...options
    });
};

/**
 * Runtime
 * return runtime in hours
 */
export const runtime = <ThrowOnError extends boolean = false>(options: Options<RuntimeData, ThrowOnError>) => {
    return (options.client ?? client).get<RuntimeResponses, RuntimeErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/nodes/{node_id}/runtime',
        ...options
    });
};

/**
 * Search
 * Search for users by username or email
 */
export const search = <ThrowOnError extends boolean = false>(options?: Options<SearchData, ThrowOnError>) => {
    return (options?.client ?? client).get<SearchResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/search/users/',
        ...options
    });
};

/**
 * Search Servers
 * Search for servers by name
 */
export const searchServers = <ThrowOnError extends boolean = false>(options?: Options<SearchServersData, ThrowOnError>) => {
    return (options?.client ?? client).get<SearchServersResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/search/servers/',
        ...options
    });
};

/**
 * Search Fs
 * Search for files in a container's filesystem
 */
export const searchFs = <ThrowOnError extends boolean = false>(options: Options<SearchFsData, ThrowOnError>) => {
    return (options.client ?? client).get<SearchFsResponses, SearchFsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/search/fs/{server_id}/{path}',
        ...options
    });
};

/**
 * Search Nodes
 * Search for nodes by name
 */
export const searchNodes = <ThrowOnError extends boolean = false>(options?: Options<SearchNodesData, ThrowOnError>) => {
    return (options?.client ?? client).get<SearchNodesResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/search/nodes/',
        ...options
    });
};

/**
 * Search Templates
 * Search for templates by name
 */
export const searchTemplates = <ThrowOnError extends boolean = false>(options?: Options<SearchTemplatesData, ThrowOnError>) => {
    return (options?.client ?? client).get<SearchTemplatesResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/search/templates/',
        ...options
    });
};

/**
 * Get Archive
 */
export const getArchive = <ThrowOnError extends boolean = false>(options: Options<GetArchiveData, ThrowOnError>) => {
    return (options.client ?? client).get<GetArchiveResponses, GetArchiveErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/volumes/{server_id}/fs/archive',
        ...options
    });
};

/**
 * Read File
 * read a file in a container volume, returns a tar archive of the file
 */
export const readFile = <ThrowOnError extends boolean = false>(options: Options<ReadFileData, ThrowOnError>) => {
    return (options.client ?? client).get<ReadFileResponses, ReadFileErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/volumes/{server_id}/fs',
        ...options
    });
};

/**
 * Upload File
 * upload a zip file to a container volume path, extracts zip and places contents in path
 */
export const uploadFile = <ThrowOnError extends boolean = false>(options: Options<UploadFileData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadFileResponses, UploadFileErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/volumes/{server_id}/fs/',
        ...options
    });
};

/**
 * Delete File
 * delete a file in a container volume
 */
export const deleteFile = <ThrowOnError extends boolean = false>(options: Options<DeleteFileData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteFileResponses, DeleteFileErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/volumes/{server_id}/fs/{path}',
        ...options
    });
};

/**
 * Handle Http Get
 */
export const handleHttpGet = <ThrowOnError extends boolean = false>(options?: Options<HandleHttpGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<HandleHttpGetResponses, HandleHttpGetErrors, ThrowOnError>({
        url: '/graphql',
        ...options
    });
};

/**
 * Handle Http Post
 */
export const handleHttpPost = <ThrowOnError extends boolean = false>(options?: Options<HandleHttpPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<HandleHttpPostResponses, unknown, ThrowOnError>({
        url: '/graphql',
        ...options
    });
};
