// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * Body_login_user_users_token_post
 */
export type BodyLoginUserUsersTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ContainerCommandResponse
 */
export type ContainerCommandResponse = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * ContainerFileDeleteResponse
 */
export type ContainerFileDeleteResponse = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * ContainerFileUploadResponse
 */
export type ContainerFileUploadResponse = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * CreateUserRequest
 */
export type CreateUserRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * NodeDiskUsageResponse
 */
export type NodeDiskUsageResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Used
     */
    used: number;
};

/**
 * NodeListResponse
 */
export type NodeListResponse = {
    /**
     * Items
     */
    items: {
        [key: string]: number;
    };
};

/**
 * NodeUptimeResponse
 */
export type NodeUptimeResponse = {
    /**
     * Uptime Hours
     */
    uptime_hours: number;
};

/**
 * NodesCreate
 */
export type NodesCreate = {
    /**
     * Name
     * Node name
     */
    name: string;
    /**
     * Cpus
     * Number of CPUs on the node
     */
    cpus: number;
    /**
     * Disk
     * Total disk space on the node in GB
     */
    disk: number;
    /**
     * Memory
     * Total memory on the node in GB
     */
    memory: number;
    /**
     * Cpu Name
     * CPU model name
     */
    cpu_name: string;
    /**
     * Max Hz
     * Maximum CPU frequency on the node in MHz
     */
    max_hz: number;
    /**
     * Arch
     * Node architecture
     */
    arch: string;
};

/**
 * NodesRead
 */
export type NodesRead = {
    /**
     * Name
     * Node name
     */
    name: string;
    /**
     * Cpus
     * Number of CPUs on the node
     */
    cpus: number;
    /**
     * Disk
     * Total disk space on the node in GB
     */
    disk: number;
    /**
     * Memory
     * Total memory on the node in GB
     */
    memory: number;
    /**
     * Cpu Name
     * CPU model name
     */
    cpu_name: string;
    /**
     * Max Hz
     * Maximum CPU frequency on the node in MHz
     */
    max_hz: number;
    /**
     * Arch
     * Node architecture
     */
    arch: string;
    /**
     * Id
     */
    id: number;
};

/**
 * ServerDeleteResponse
 */
export type ServerDeleteResponse = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * ServerFileListResponse
 */
export type ServerFileListResponse = {
    /**
     * Items
     */
    items: Array<string>;
};

/**
 * ServerListResponse
 */
export type ServerListResponse = {
    /**
     * Items
     */
    items: {
        [key: string]: number;
    };
};

/**
 * ServerStartResponse
 */
export type ServerStartResponse = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * ServerStatusResponse
 */
export type ServerStatusResponse = {
    /**
     * Running
     */
    running: boolean;
    /**
     * Health
     */
    health?: string | null;
};

/**
 * ServerStopResponse
 */
export type ServerStopResponse = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * ServersCreate
 */
export type ServersCreate = {
    /**
     * Name
     * Server name
     */
    name: string;
    /**
     * Env
     * JSON string of environment variables for the server
     */
    env: {
        [key: string]: string;
    };
    /**
     * Cpu
     * CPU resources allocated to the server
     */
    cpu: number | null;
    /**
     * Disk
     * Disk space allocated to the server in GB
     */
    disk: number | null;
    /**
     * Memory
     * Memory allocated to the server in GB
     */
    memory: number | null;
    /**
     * Container Name
     * Docker container name for the server
     */
    container_name?: string;
    /**
     * Node Id
     */
    node_id: number;
    /**
     * Template Id
     */
    template_id: number;
    /**
     * Tags
     * Comma-separated tags for the server
     */
    tags?: Array<string>;
};

/**
 * ServersRead
 */
export type ServersRead = {
    /**
     * Name
     * Server name
     */
    name: string;
    /**
     * Env
     * JSON string of environment variables for the server
     */
    env: {
        [key: string]: string;
    };
    /**
     * Cpu
     * CPU resources allocated to the server
     */
    cpu: number | null;
    /**
     * Disk
     * Disk space allocated to the server in GB
     */
    disk: number | null;
    /**
     * Memory
     * Memory allocated to the server in GB
     */
    memory: number | null;
    /**
     * Container Name
     * Docker container name for the server
     */
    container_name?: string;
    /**
     * Node Id
     */
    node_id: number;
    /**
     * Template Id
     */
    template_id: number;
    /**
     * Tags
     * Comma-separated tags for the server
     */
    tags?: Array<string>;
    /**
     * Id
     */
    id: number;
    /**
     * Port
     */
    port: Array<number>;
    /**
     * Linked Users
     */
    linked_users?: Array<UsersRead>;
};

/**
 * TemplateCreateResponse
 */
export type TemplateCreateResponse = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * TemplateDeleteResponse
 */
export type TemplateDeleteResponse = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * TemplateListResponse
 */
export type TemplateListResponse = {
    /**
     * Items
     */
    items: {
        [key: string]: number;
    };
};

/**
 * TemplatesCreate
 */
export type TemplatesCreate = {
    /**
     * Name
     * Template name
     */
    name: string;
    /**
     * Image
     * Docker image name
     */
    image: string;
    /**
     * Tags
     * Comma-separated tags for the template
     */
    tags: Array<string>;
    /**
     * Exposed Port
     * List of ports that are exposed by the template
     */
    exposed_port: Array<number>;
    /**
     * Exposed Volume
     * List of volumes that are exposed by the template.
     */
    exposed_volume?: Array<string> | null;
    /**
     * Modules
     * JSON string of "Modules" that will be added to server creator UI
     */
    modules: Array<string> | null;
    /**
     * Description
     * Template description
     */
    description?: string | null;
    /**
     * Resource Min Cpu
     * Minimum CPU resources required
     */
    resource_min_cpu: number | null;
    /**
     * Resource Min Disk
     * Minimum Disk resources required
     */
    resource_min_disk: number | null;
    /**
     * Resource Min Mem
     * Minimum Memory resources required
     */
    resource_min_mem: number | null;
};

/**
 * TemplatesRead
 */
export type TemplatesRead = {
    /**
     * Name
     * Template name
     */
    name: string;
    /**
     * Image
     * Docker image name
     */
    image: string;
    /**
     * Tags
     * Comma-separated tags for the template
     */
    tags: Array<string>;
    /**
     * Exposed Port
     * List of ports that are exposed by the template
     */
    exposed_port: Array<number>;
    /**
     * Exposed Volume
     * List of volumes that are exposed by the template.
     */
    exposed_volume?: Array<string> | null;
    /**
     * Modules
     * JSON string of "Modules" that will be added to server creator UI
     */
    modules: Array<string> | null;
    /**
     * Description
     * Template description
     */
    description?: string | null;
    /**
     * Resource Min Cpu
     * Minimum CPU resources required
     */
    resource_min_cpu: number | null;
    /**
     * Resource Min Disk
     * Minimum Disk resources required
     */
    resource_min_disk: number | null;
    /**
     * Resource Min Mem
     * Minimum Memory resources required
     */
    resource_min_mem: number | null;
    /**
     * Id
     */
    id: number;
};

/**
 * UserListResponse
 */
export type UserListResponse = {
    /**
     * Items
     */
    items: {
        [key: string]: number;
    };
};

/**
 * UsersBase
 */
export type UsersBase = {
    /**
     * Username
     * Username
     */
    username: string;
    /**
     * Disabled
     */
    disabled?: boolean;
    /**
     * Scopes
     * List of scopes assigned to the user
     */
    scopes: Array<string> | null;
    /**
     * Admin
     */
    admin?: boolean;
};

/**
 * UsersRead
 */
export type UsersRead = {
    /**
     * Username
     * Username
     */
    username: string;
    /**
     * Disabled
     */
    disabled?: boolean;
    /**
     * Scopes
     * List of scopes assigned to the user
     */
    scopes: Array<string> | null;
    /**
     * Admin
     */
    admin?: boolean;
    /**
     * Id
     */
    id: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * CreateUserRequest
 */
export type CreateUserRequestWritable = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
};

export type AddTemplateData = {
    body: TemplatesCreate;
    path?: never;
    query?: never;
    url: '/templates/';
};

export type AddTemplateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddTemplateError = AddTemplateErrors[keyof AddTemplateErrors];

export type AddTemplateResponses = {
    /**
     * Successful Response
     */
    200: TemplateCreateResponse;
};

export type AddTemplateResponse = AddTemplateResponses[keyof AddTemplateResponses];

export type GetTemplateData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: number;
    };
    query?: never;
    url: '/templates/{template_id}';
};

export type GetTemplateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTemplateError = GetTemplateErrors[keyof GetTemplateErrors];

export type GetTemplateResponses = {
    /**
     * Successful Response
     */
    200: TemplatesRead;
};

export type GetTemplateResponse = GetTemplateResponses[keyof GetTemplateResponses];

export type UpdateTemplateData = {
    body: TemplatesCreate;
    path: {
        /**
         * Template Id
         */
        template_id: number;
    };
    query?: never;
    url: '/templates/{template_id}';
};

export type UpdateTemplateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTemplateError = UpdateTemplateErrors[keyof UpdateTemplateErrors];

export type UpdateTemplateResponses = {
    /**
     * Successful Response
     */
    200: TemplateCreateResponse;
};

export type UpdateTemplateResponse = UpdateTemplateResponses[keyof UpdateTemplateResponses];

export type DeleteTemplateData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Template Id
         */
        template_id: number;
    };
    url: '/templates/{name}/delete';
};

export type DeleteTemplateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTemplateError = DeleteTemplateErrors[keyof DeleteTemplateErrors];

export type DeleteTemplateResponses = {
    /**
     * Successful Response
     */
    200: TemplateDeleteResponse;
};

export type DeleteTemplateResponse = DeleteTemplateResponses[keyof DeleteTemplateResponses];

export type DeleteUserAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type DeleteUserAccountResponses = {
    /**
     * Response Delete User Account Users  Delete
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteUserAccountResponse = DeleteUserAccountResponses[keyof DeleteUserAccountResponses];

export type CreateUserAccountData = {
    body: CreateUserRequestWritable;
    path?: never;
    query?: never;
    url: '/users/';
};

export type CreateUserAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserAccountError = CreateUserAccountErrors[keyof CreateUserAccountErrors];

export type CreateUserAccountResponses = {
    /**
     * Successful Response
     */
    200: UsersBase;
};

export type CreateUserAccountResponse = CreateUserAccountResponses[keyof CreateUserAccountResponses];

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/refresh';
};

export type RefreshTokenResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginUserData = {
    body: BodyLoginUserUsersTokenPost;
    path?: never;
    query?: never;
    url: '/users/token';
};

export type LoginUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors];

export type LoginUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/revoke';
};

export type LogoutUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: UsersBase;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type CreateServerData = {
    body: ServersCreate;
    path?: never;
    query?: never;
    url: '/servers/';
};

export type CreateServerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateServerError = CreateServerErrors[keyof CreateServerErrors];

export type CreateServerResponses = {
    /**
     * Successful Response
     */
    200: ServersRead;
};

export type CreateServerResponse = CreateServerResponses[keyof CreateServerResponses];

export type DeleteServerData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: number;
    };
    query?: never;
    url: '/servers/{server_id}';
};

export type DeleteServerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteServerError = DeleteServerErrors[keyof DeleteServerErrors];

export type DeleteServerResponses = {
    /**
     * Successful Response
     */
    200: ServerDeleteResponse;
};

export type DeleteServerResponse = DeleteServerResponses[keyof DeleteServerResponses];

export type GetServerInfoData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: number;
    };
    query?: never;
    url: '/servers/{server_id}';
};

export type GetServerInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetServerInfoError = GetServerInfoErrors[keyof GetServerInfoErrors];

export type GetServerInfoResponses = {
    /**
     * Successful Response
     */
    200: ServersRead;
};

export type GetServerInfoResponse = GetServerInfoResponses[keyof GetServerInfoResponses];

export type StartServerData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: number;
    };
    query?: never;
    url: '/servers/{server_id}/start';
};

export type StartServerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartServerError = StartServerErrors[keyof StartServerErrors];

export type StartServerResponses = {
    /**
     * Successful Response
     */
    200: ServerStartResponse;
};

export type StartServerResponse = StartServerResponses[keyof StartServerResponses];

export type StopServerData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: number;
    };
    query?: never;
    url: '/servers/{server_id}/stop';
};

export type StopServerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopServerError = StopServerErrors[keyof StopServerErrors];

export type StopServerResponses = {
    /**
     * Successful Response
     */
    200: ServerStopResponse;
};

export type StopServerResponse = StopServerResponses[keyof StopServerResponses];

export type GetServerStatusData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: number;
    };
    query?: never;
    url: '/servers/{server_id}/status';
};

export type GetServerStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetServerStatusError = GetServerStatusErrors[keyof GetServerStatusErrors];

export type GetServerStatusResponses = {
    /**
     * Response Get Server Status Servers  Server Id  Status Get
     * Successful Response
     */
    200: ServerStatusResponse | null;
};

export type GetServerStatusResponse = GetServerStatusResponses[keyof GetServerStatusResponses];

export type SendCommandData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: number;
    };
    query: {
        /**
         * Command
         */
        command: string;
    };
    url: '/servers/{server_id}/command';
};

export type SendCommandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendCommandError = SendCommandErrors[keyof SendCommandErrors];

export type SendCommandResponses = {
    /**
     * Successful Response
     */
    200: ContainerCommandResponse;
};

export type SendCommandResponse = SendCommandResponses[keyof SendCommandResponses];

export type AddNodeData = {
    body: NodesCreate;
    path?: never;
    query?: never;
    url: '/nodes/';
};

export type AddNodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddNodeError = AddNodeErrors[keyof AddNodeErrors];

export type AddNodeResponses = {
    /**
     * Successful Response
     */
    200: NodesRead;
};

export type AddNodeResponse = AddNodeResponses[keyof AddNodeResponses];

export type DeleteNodeData = {
    body?: never;
    path: {
        /**
         * Node Id
         */
        node_id: number;
    };
    query?: never;
    url: '/nodes/{node_id}';
};

export type DeleteNodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteNodeError = DeleteNodeErrors[keyof DeleteNodeErrors];

export type DeleteNodeResponses = {
    /**
     * Response Delete Node Nodes  Node Id  Delete
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteNodeResponse = DeleteNodeResponses[keyof DeleteNodeResponses];

export type GetNodeData = {
    body?: never;
    path: {
        /**
         * Node Id
         */
        node_id: number;
    };
    query?: never;
    url: '/nodes/{node_id}';
};

export type GetNodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNodeError = GetNodeErrors[keyof GetNodeErrors];

export type GetNodeResponses = {
    /**
     * Successful Response
     */
    200: NodesRead;
};

export type GetNodeResponse = GetNodeResponses[keyof GetNodeResponses];

export type DiskUsageData = {
    body?: never;
    path: {
        /**
         * Node Id
         */
        node_id: number;
    };
    query?: never;
    url: '/nodes/{node_id}/disk_usage';
};

export type DiskUsageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DiskUsageError = DiskUsageErrors[keyof DiskUsageErrors];

export type DiskUsageResponses = {
    /**
     * Successful Response
     */
    200: NodeDiskUsageResponse;
};

export type DiskUsageResponse = DiskUsageResponses[keyof DiskUsageResponses];

export type RuntimeData = {
    body?: never;
    path: {
        /**
         * Node Id
         */
        node_id: number;
    };
    query?: never;
    url: '/nodes/{node_id}/runtime';
};

export type RuntimeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeError = RuntimeErrors[keyof RuntimeErrors];

export type RuntimeResponses = {
    /**
     * Successful Response
     */
    200: NodeUptimeResponse;
};

export type RuntimeResponse = RuntimeResponses[keyof RuntimeResponses];

export type SearchData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/search/users/';
};

export type SearchResponses = {
    /**
     * Successful Response
     */
    200: UserListResponse;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type SearchServersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/search/servers/';
};

export type SearchServersResponses = {
    /**
     * Successful Response
     */
    200: ServerListResponse;
};

export type SearchServersResponse = SearchServersResponses[keyof SearchServersResponses];

export type SearchFsData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: number;
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/search/fs/{server_id}/{path}';
};

export type SearchFsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchFsError = SearchFsErrors[keyof SearchFsErrors];

export type SearchFsResponses = {
    /**
     * Successful Response
     */
    200: ServerFileListResponse;
};

export type SearchFsResponse = SearchFsResponses[keyof SearchFsResponses];

export type SearchNodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/search/nodes/';
};

export type SearchNodesResponses = {
    /**
     * Successful Response
     */
    200: NodeListResponse;
};

export type SearchNodesResponse = SearchNodesResponses[keyof SearchNodesResponses];

export type SearchTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/search/templates/';
};

export type SearchTemplatesResponses = {
    /**
     * Successful Response
     */
    200: TemplateListResponse;
};

export type SearchTemplatesResponse = SearchTemplatesResponses[keyof SearchTemplatesResponses];

export type GetArchiveData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: number;
    };
    query?: {
        /**
         * Paths
         */
        paths?: string | null;
    };
    url: '/volumes/{server_id}/fs/archive';
};

export type GetArchiveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetArchiveError = GetArchiveErrors[keyof GetArchiveErrors];

export type GetArchiveResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteFileData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: number;
    };
    query: {
        /**
         * Path
         * Absolute path to file
         */
        path: string;
    };
    url: '/volumes/{server_id}/fs';
};

export type DeleteFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFileError = DeleteFileErrors[keyof DeleteFileErrors];

export type DeleteFileResponses = {
    /**
     * Successful Response
     */
    200: ContainerFileDeleteResponse;
};

export type DeleteFileResponse = DeleteFileResponses[keyof DeleteFileResponses];

export type ReadFileData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: number;
    };
    query: {
        /**
         * Path
         * Absolute path to file
         */
        path: string;
    };
    url: '/volumes/{server_id}/fs';
};

export type ReadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileError = ReadFileErrors[keyof ReadFileErrors];

export type ReadFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadFileData = {
    body: Blob | File;
    path: {
        /**
         * Server Id
         */
        server_id: number;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/volumes/{server_id}/fs/';
};

export type UploadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
    /**
     * Successful Response
     */
    200: ContainerFileUploadResponse;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type HandleHttpGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/graphql';
};

export type HandleHttpGetErrors = {
    /**
     * Not found if GraphiQL or query via GET are not enabled.
     */
    404: unknown;
};

export type HandleHttpGetResponses = {
    /**
     * The GraphiQL integrated development environment.
     */
    200: unknown;
};

export type HandleHttpPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/graphql';
};

export type HandleHttpPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
