// This file is auto-generated by @hey-api/openapi-ts

/**
 * ContainerListResponse
 */
export type ContainerListResponse = {
    /**
     * Container
     */
    container: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Resource
 */
export type Resource = {
    /**
     * Cpu
     * The number of CPU cores allocated to the container.
     */
    cpu?: number | null;
    /**
     * Memory
     * The amount of memory allocated to the container, e.g., '2G' for 2 gigabytes.
     */
    memory?: string | null;
};

/**
 * RunningResponse
 */
export type RunningResponse = {
    /**
     * Running
     */
    running: boolean;
};

/**
 * SuccessResponse
 */
export type SuccessResponse = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * Template
 */
export type Template = {
    /**
     * Name
     * The name of the template.
     */
    name: string;
    /**
     * Image
     * The name of the Docker image to use for the container.
     */
    image: string;
    /**
     * Tags
     * Additional Tags for the Docker image. defaults to 'latest'.
     */
    tags?: Array<string> | null;
    /**
     * Description
     * A brief description of the template.
     */
    description?: string | null;
    /**
     * Minimum resource requirements/allocated for the container.
     */
    resource?: Resource | null;
    /**
     * Env
     */
    env?: Array<string | {
        [key: string]: string;
    }> | null;
    /**
     * Extra Args
     */
    extra_args?: string | Array<string> | null;
};

/**
 * TemplateListResponse
 */
export type TemplateListResponse = {
    /**
     * Template
     */
    template: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListContainersApiContainerListGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/container/list';
};

export type ListContainersApiContainerListGetResponses = {
    /**
     * Successful Response
     */
    200: ContainerListResponse;
};

export type ListContainersApiContainerListGetResponse = ListContainersApiContainerListGetResponses[keyof ListContainersApiContainerListGetResponses];

export type StartContainerApiContainerNameStartGetData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/container/{name}/start';
};

export type StartContainerApiContainerNameStartGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartContainerApiContainerNameStartGetError = StartContainerApiContainerNameStartGetErrors[keyof StartContainerApiContainerNameStartGetErrors];

export type StartContainerApiContainerNameStartGetResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type StartContainerApiContainerNameStartGetResponse = StartContainerApiContainerNameStartGetResponses[keyof StartContainerApiContainerNameStartGetResponses];

export type StopContainerApiContainerNameStopGetData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/container/{name}/stop';
};

export type StopContainerApiContainerNameStopGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopContainerApiContainerNameStopGetError = StopContainerApiContainerNameStopGetErrors[keyof StopContainerApiContainerNameStopGetErrors];

export type StopContainerApiContainerNameStopGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateContainerApiContainerCreateTemplateNamePostData = {
    body?: never;
    path: {
        /**
         * Template Name
         */
        template_name: string;
    };
    query?: never;
    url: '/api/container/create/{template_name}';
};

export type CreateContainerApiContainerCreateTemplateNamePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateContainerApiContainerCreateTemplateNamePostError = CreateContainerApiContainerCreateTemplateNamePostErrors[keyof CreateContainerApiContainerCreateTemplateNamePostErrors];

export type CreateContainerApiContainerCreateTemplateNamePostResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type CreateContainerApiContainerCreateTemplateNamePostResponse = CreateContainerApiContainerCreateTemplateNamePostResponses[keyof CreateContainerApiContainerCreateTemplateNamePostResponses];

export type GetContainerStatusApiContainerContainerNameStatusGetData = {
    body?: never;
    path: {
        /**
         * Container Name
         */
        container_name: string;
    };
    query?: never;
    url: '/api/container/{container_name}/status';
};

export type GetContainerStatusApiContainerContainerNameStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContainerStatusApiContainerContainerNameStatusGetError = GetContainerStatusApiContainerContainerNameStatusGetErrors[keyof GetContainerStatusApiContainerContainerNameStatusGetErrors];

export type GetContainerStatusApiContainerContainerNameStatusGetResponses = {
    /**
     * Successful Response
     */
    200: RunningResponse;
};

export type GetContainerStatusApiContainerContainerNameStatusGetResponse = GetContainerStatusApiContainerContainerNameStatusGetResponses[keyof GetContainerStatusApiContainerContainerNameStatusGetResponses];

export type GetContainerMetricsApiContainerContainerNameMetricsGetData = {
    body?: never;
    path: {
        /**
         * Container Name
         */
        container_name: string;
    };
    query?: never;
    url: '/api/container/{container_name}/metrics';
};

export type GetContainerMetricsApiContainerContainerNameMetricsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContainerMetricsApiContainerContainerNameMetricsGetError = GetContainerMetricsApiContainerContainerNameMetricsGetErrors[keyof GetContainerMetricsApiContainerContainerNameMetricsGetErrors];

export type GetContainerMetricsApiContainerContainerNameMetricsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetLogMessageApiContainerContainerNameLogsGetData = {
    body?: never;
    path: {
        /**
         * Container Name
         */
        container_name: string;
    };
    query?: {
        /**
         * Line Count
         */
        line_count?: number | null;
    };
    url: '/api/container/{container_name}/logs';
};

export type GetLogMessageApiContainerContainerNameLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLogMessageApiContainerContainerNameLogsGetError = GetLogMessageApiContainerContainerNameLogsGetErrors[keyof GetLogMessageApiContainerContainerNameLogsGetErrors];

export type GetLogMessageApiContainerContainerNameLogsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListTemplatesApiTemplateListGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/template/list';
};

export type ListTemplatesApiTemplateListGetResponses = {
    /**
     * Successful Response
     */
    200: TemplateListResponse;
};

export type ListTemplatesApiTemplateListGetResponse = ListTemplatesApiTemplateListGetResponses[keyof ListTemplatesApiTemplateListGetResponses];

export type GetTemplateNameApiTemplateNameGetData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/template/{name}';
};

export type GetTemplateNameApiTemplateNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTemplateNameApiTemplateNameGetError = GetTemplateNameApiTemplateNameGetErrors[keyof GetTemplateNameApiTemplateNameGetErrors];

export type GetTemplateNameApiTemplateNameGetResponses = {
    /**
     * Successful Response
     */
    200: Template;
};

export type GetTemplateNameApiTemplateNameGetResponse = GetTemplateNameApiTemplateNameGetResponses[keyof GetTemplateNameApiTemplateNameGetResponses];

export type AddTemplateApiTemplateAddTemplatePostData = {
    body: Template;
    path?: never;
    query?: never;
    url: '/api/template/add_template';
};

export type AddTemplateApiTemplateAddTemplatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddTemplateApiTemplateAddTemplatePostError = AddTemplateApiTemplateAddTemplatePostErrors[keyof AddTemplateApiTemplateAddTemplatePostErrors];

export type AddTemplateApiTemplateAddTemplatePostResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type AddTemplateApiTemplateAddTemplatePostResponse = AddTemplateApiTemplateAddTemplatePostResponses[keyof AddTemplateApiTemplateAddTemplatePostResponses];

export type DeleteTemplateApiTemplateNameDeletePostData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/template/{name}/delete';
};

export type DeleteTemplateApiTemplateNameDeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTemplateApiTemplateNameDeletePostError = DeleteTemplateApiTemplateNameDeletePostErrors[keyof DeleteTemplateApiTemplateNameDeletePostErrors];

export type DeleteTemplateApiTemplateNameDeletePostResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type DeleteTemplateApiTemplateNameDeletePostResponse = DeleteTemplateApiTemplateNameDeletePostResponses[keyof DeleteTemplateApiTemplateNameDeletePostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};